time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_0.ini >> job_1_2_image_mix_0.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_1.ini >> job_1_2_image_mix_1.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_2.ini >> job_1_2_image_mix_2.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_3.ini >> job_1_2_image_mix_3.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_4.ini >> job_1_2_image_mix_4.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_5.ini >> job_1_2_image_mix_5.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_6.ini >> job_1_2_image_mix_6.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_7.ini >> job_1_2_image_mix_7.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_8.ini >> job_1_2_image_mix_8.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_9.ini >> job_1_2_image_mix_9.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_10.ini >> job_1_2_image_mix_10.txt
time mpirun -np 2 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_11.ini >> job_1_2_image_mix_11.txt

time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_0.ini >> job_1_4_image_mix_0.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_1.ini >> job_1_4_image_mix_1.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_2.ini >> job_1_4_image_mix_2.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_3.ini >> job_1_4_image_mix_3.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_4.ini >> job_1_4_image_mix_4.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_5.ini >> job_1_4_image_mix_5.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_6.ini >> job_1_4_image_mix_6.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_7.ini >> job_1_4_image_mix_7.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_8.ini >> job_1_4_image_mix_8.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_9.ini >> job_1_4_image_mix_9.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_10.ini >> job_1_4_image_mix_10.txt
time mpirun -np 4 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_11.ini >> job_1_4_image_mix_11.txt

time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_0.ini >> job_1_8_image_mix_0.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_1.ini >> job_1_8_image_mix_1.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_2.ini >> job_1_8_image_mix_2.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_3.ini >> job_1_8_image_mix_3.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_4.ini >> job_1_8_image_mix_4.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_5.ini >> job_1_8_image_mix_5.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_6.ini >> job_1_8_image_mix_6.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_7.ini >> job_1_8_image_mix_7.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_8.ini >> job_1_8_image_mix_8.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_9.ini >> job_1_8_image_mix_9.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_10.ini >> job_1_8_image_mix_10.txt
time mpirun -np 8 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_11.ini >> job_1_8_image_mix_11.txt

time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_0.ini >> job_1_16_image_mix_0.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_1.ini >> job_1_16_image_mix_1.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_2.ini >> job_1_16_image_mix_2.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_3.ini >> job_1_16_image_mix_3.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_4.ini >> job_1_16_image_mix_4.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_5.ini >> job_1_16_image_mix_5.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_6.ini >> job_1_16_image_mix_6.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_7.ini >> job_1_16_image_mix_7.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_8.ini >> job_1_16_image_mix_8.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_9.ini >> job_1_16_image_mix_9.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_10.ini >> job_1_16_image_mix_10.txt
time mpirun -np 16 -f Malone/machinefiles ./Malone/malone -a 4 -e img_mix_11.ini >> job_1_16_image_mix_11.txt

